insert into orders (title, description, price) values ('Sauce - Apple, Unsweetened', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Puff Pastry - Sheets', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Calypso - Lemonade', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Oil - Truffle, Black', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bagel - 12 Grain Preslice', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cocoa Butter', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Parsnip', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Turkey - Breast, Boneless Sk On', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Ice Cream Bar - Rolo Cone', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Shrimp - Black Tiger 6 - 8', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - White, Pinot Grigio', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Potatoes - Instant, Mashed', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cinnamon Buns Sticky', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Leeks - Baby, White', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Red, Antinori Santa', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sun - Dried Tomatoes', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Spinach - Baby', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Silicone Parch. 16.3x24.3', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tomatoes - Roma', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Doilies - 5, Paper', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bar Mix - Lemon', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Croissants Thaw And Serve', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lettuce - Baby Salad Greens', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Galliano', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup - French Can Pea', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Glucose', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Crab - Claws, 26 - 30', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Chocolate - Dark', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Club Soda - Schweppes, 355 Ml', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Lasagne, Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cod - Black Whole Fillet', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Water - Perrier', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Apricots - Halves', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Southern Comfort', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Vanilla Beans', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup - French Can Pea', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Neckerchief Blck', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tea - Darjeeling, Azzura', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tomatoes - Cherry', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tomatoes Tear Drop Yellow', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Glass Clear 8 Oz', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - 10 Grain', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cheese - Roquefort Pappillon', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cookies - Oreo, 4 Pack', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beans - Navy, Dry', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pie Shells 10', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pepper - Green', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Curry Paste - Green Masala', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Lasagna Noodle, Frozen', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sage - Ground', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Fenngreek Seed', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Glaze - Apricot', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - Multigrain Oval', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Napkin - Dinner, White', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Coconut - Shredded, Unsweet', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Zinfandel Rosenblum', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pork - Backfat', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread Base - Italian', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cheese - Asiago', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Yucca', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Nut - Almond, Blanched, Sliced', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Nantuket Peach Orange', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Crawfish', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Saskatoon Berries - Frozen', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pork - Ham, Virginia', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Mints - Striped Red', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Salt And Pepper Mix - Black', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sprouts - Bean', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Chicken - White Meat, No Tender', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Lasagna, Dry', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cabbage Roll', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Clam Nectar', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Raisin - Dark', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Angel Hair', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Broom - Push', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beer - Guiness', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Green Tea Refresher', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pepper - Julienne, Frozen', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Chocolate - Milk', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - Mini Hamburger Bun', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Jackson Triggs Okonagan', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Chocolate - White', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wasabi Paste', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Red Snapper - Fillet, Skin On', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cabbage - Red', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Coffee - French Vanilla Frothy', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Jam - Apricot', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Apron', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Table Cloth 62x114 White', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Juice - Propel Sport', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bacardi Limon', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Trimbach Pinot Blanc', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Burger Veggie', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Graham Cracker Mix', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Turkey - Breast, Bone - In', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Casillero Del Diablo', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('The Pop Shoppe Pinapple', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Squeeze Bottle', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lettuce - Arugula', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beer - Sleeman Fine Porter', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Corn - Mini', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cocoa Butter', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Garlic', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Ecolab - Solid Fusion', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Food Colouring - Blue', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beer - Steamwhistle', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Penne Primavera, Single', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Muffin Hinge 117n', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wood Chips - Regular', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Thyme - Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Greens Mustard', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tuna - Salad Premix', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Mushroom - Porcini Frozen', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup - Campbells - Tomato', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Muffin - Mix - Strawberry Rhubarb', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Assorted Desserts', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Amarula Cream', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Red Currant Jelly', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup Campbells - Italian Wedding', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Yogurt - Assorted Pack', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Orange Roughy 4/6 Oz', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - 10 Grain Parisian', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Muffin - Mix - Bran And Maple 15l', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Lou Black Shiraz', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Eggplant Oriental', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Veal - Provimi Inside', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Nut - Pecan, Halves', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Red, Mouton Cadet', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pasta - Canelloni', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup V8 Roasted Red Pepper', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Juice - Clam, 46 Oz', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Quail - Eggs, Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Calvados - Boulard', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bagelers', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pate - Cognac', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Veal - Eye Of Round', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beer - Steamwhistle', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sugar - Invert', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Island Oasis - Magarita Mix', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Olives - Morracan Dired', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lobster - Live', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Saskatoon Berries - Frozen', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cheese - Mozzarella, Buffalo', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sour Cream', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Artichoke - Hearts, Canned', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pecan Raisin - Tarts', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sambuca - Ramazzotti', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lobster - Live', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lobster - Tail, 3 - 4 Oz', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Onion - Dried', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cup - 3.5oz, Foam', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Ostrich - Fan Fillet', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Smoked Tongue', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lychee - Canned', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lettuce - Treviso', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('C - Plus, Orange', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bacardi Breezer - Tropical', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pepper - Gypsy Pepper', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Olives - Kalamata', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cheese - St. Paulin', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Muffin - Mix - Mango Sour Cherry', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sambuca Cream', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pie Shells 10', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Green Scrubbie Pad H.duty', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - Olive Dinner Roll', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cranberries - Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Silicone Paper 16.5x24', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cake - Dulce De Leche', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Shrimp - Black Tiger 13/15', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Tuna - Canned, Flaked, Light', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Broom - Push', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup - Campbells Tomato Ravioli', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pears - Anjou', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pork - Shoulder', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pickerel - Fillets', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Zinfandel Rosenblum', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Marjoram - Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Salad Dressing', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Delicato Merlot', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Cheese Cheddar Processed', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pear - Packum', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Lamb - Whole Head Off', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Glucose', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Sauce - Ranch Dressing', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Pop - Club Soda Can', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Bread - Triangle White', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Buttons', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Soup Knorr Chili With Beans', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Milk - 2% 250 Ml', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Appetizer - Seafood Assortment', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Clams - Canned', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Ecolab Silver Fusion', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Chicken - Ground', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Wine - Fino Tio Pepe Gonzalez', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Jam - Marmalade, Orange', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Monkfish - Fresh', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Beer - True North Strong Ale', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Mushrooms - Honey', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Flour - Bran, Red', 'error: no such column: grocery', 'error: no such column: grocery');
insert into orders (title, description, price) values ('Longos - Chicken Caeser Salad', 'error: no such column: grocery', 'error: no such column: grocery');
